version: "3"

services:
  # Webserver
  webserver:
    build:
      context: ./bin/webserver
    container_name: "webserver"
    restart: "always"
    ports:
      - "${UNSECURE_HOST_PORT}:80"
      - "${SECURE_HOST_PORT}:443"
    links:
      - mysql
    volumes:
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${APACHE_CONFIG-./config/apache2/apache2.conf}:/etc/apache2/apache2.conf
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  # API Server
  apiserver:
    build:
      context: ./bin/apiserver
    container_name: "apiserver"
    restart: "always"
    ports:
      - "${APISERVER_PORT}:5000"
    links:
      - webserver
      - mysql
  # MySQL Server
  mysql:
    build: ./bin/mysql
    container_name: "mysql"
    restart: "always"
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  # PHPMyAdmin server
  phpmyadmin:
    build: ./bin/phpmyadmin
    container_name: "phpmyadmin"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${HOST_MACHINE_MYSQL_PORT}
      ports:
        - "${PHPMYADMIN_PORT}:80"
      volumes:
        - /sessions
